baseURL = 'https://reese9997.github.io/'
languageCode = 'zh-tw'
title = '東海大學'
theme = 'ananke'


[params.ananke.social.share]
networks = ["email", "facebook", "linkedin","instagram"]

[params.ananke.social.follow]
networks = ["facebook","linkedin","instagram"]

[params.ananke.social.facebook]
username = "林巧翎"
profilelink = "https://www.facebook.com/share/17dynABG4m/?mibextid=LQQJ4d"

[params.ananke.social.linkedin]
username = "林巧翎"
profilelink = "https://www.linkedin.com/in/stephanie-undefined-48b5b72b7/"

[params.ananke.social.instagram]
username = "cllin_1019"


[params]
text_color = ""
author = "林巧翎"
favicon = ""
site_logo = "logo5.png"
description = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-washed-red"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 0





